# Generated by Django 5.0.1 on 2024-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('descripation', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('img1', models.ImageField(null=True, upload_to='media')),
                ('img2', models.ImageField(null=True, upload_to='media')),
                ('img3', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
