# Generated by Django 5.0.1 on 2024-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, null=True)),
                ('capacity', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=100)),
                ('img1', models.ImageField(null=True, upload_to='media')),
                ('img2', models.ImageField(null=True, upload_to='media')),
                ('img3', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
