# Generated by Django 5.0.1 on 2024-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_roomproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproduct',
            name='price',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
