# Generated by Django 5.0.1 on 2024-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_roomproduct_price_roomproduct_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproduct',
            name='time1',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='view',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
