# Generated by Django 5.0.1 on 2024-01-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_roomproduct_time1_roomproduct_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
