# Generated by Django 5.0.1 on 2024-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_roomproduct_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, null=True)),
                ('capacity', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('startdate', models.TimeField(auto_now=True, null=True)),
                ('enddate', models.TimeField(auto_now=True, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=100)),
                ('img1', models.ImageField(null=True, upload_to='media')),
                ('img2', models.ImageField(null=True, upload_to='media')),
                ('img3', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
