# Generated by Django 5.0.1 on 2024-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_roomoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='dining',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dish',
            new_name='dtype',
        ),
        migrations.AlterField(
            model_name='roomoffer',
            name='enddate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomoffer',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='roomoffer',
            name='startdate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
