# Generated by Django 5.0.1 on 2024-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_rename_price_product_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='time',
            new_name='dtime',
        ),
        migrations.AddField(
            model_name='product',
            name='dresscode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ntime',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
