# Generated by Django 5.0.1 on 2024-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_rename_time_product_dtime_product_dresscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
