# Generated by Django 5.0.1 on 2024-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_alter_product_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproduct',
            name='accessible_features',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='bath_bathroom_features',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='beds_bedding',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='entertainment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='food_beverages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='furniture_furnishings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='hospitality_services',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='internet_phones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='kitchen_features',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomproduct',
            name='room_eatures',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
