# Generated by Django 5.0.1 on 2024-02-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_roomproduct_accessible_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomproduct',
            old_name='room_eatures',
            new_name='room_features',
        ),
    ]
