# Generated by Django 5.0.1 on 2024-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_rename_room_eatures_roomproduct_room_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoffer',
            name='include',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomoffer',
            name='needknow',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
