# Generated by Django 5.0.1 on 2024-02-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0012_roomoffer_include_roomoffer_needknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomoffer',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
