# Generated by Django 5.0.1 on 2024-02-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0013_alter_roomoffer_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomoffer',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
