# Generated by Django 5.0 on 2024-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0015_alter_roomoffer_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
