# Generated by Django 5.0 on 2024-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0017_alter_product_day_alter_product_dining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prebooking',
            field=models.IntegerField(null=True),
        ),
    ]
