# Generated by Django 5.0 on 2024-02-12 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0018_product_prebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturent', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('adult', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('childern', models.CharField(max_length=100, null=True)),
                ('prebooking', models.FloatField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('cnumber', models.IntegerField()),
                ('number', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
