# Generated by Django 5.0 on 2024-02-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0019_diningbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diningbooking',
            old_name='childern',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='diningbooking',
            old_name='resturent',
            new_name='restaurant',
        ),
    ]
