# Generated by Django 5.0 on 2024-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0020_rename_childern_diningbooking_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningbooking',
            name='cnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
