# Generated by Django 5.0 on 2024-02-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0022_alter_diningbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningbooking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.product'),
        ),
    ]
